#!/bin/bash

echo "hi this script was created for test"
echo "if you have file which its format like this => ip port username:password <= >
echo ""

#read file--------------------
read -p "enter your file path : " filename

if [ -a $filename ]
then
        echo "great we get this"
else
        echo "something went wrong"
fi
  
re="*[[:space:]]*"
#help for format  input
while read -n1  line
do
        echo $line

        if [[ $line = "${str%[[:space:]]*}" ]]
		then
                        echo "the space of ip is ok" 

                        if  [[ $line = "${str%[[:space:]]*}" ]]
                                then 
                                        echo "the space of port is ok"
					if  [[ $line =~ (?:*) ]]
                                                then
                                                        echo "the colon of usernam is ok">
                                                else
                                                        echo "--"

						 fi
                                else
                                        echo "--"
                        fi
                else
                        echo "--"
  fi


done < $filename
